#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.tFr43
    set site_3_0 $base.tFr72
    set site_4_0 $site_3_0.scr77
    set site_3_0 $base.tFr78
    set site_4_0 $site_3_0.scr83
    set site_3_0 $base.tFr38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d8d8d8} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x785+525+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5764 1057
    wm minsize $top 140 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "BCS Cordination Email Generator"
    vTcl:DefineAlias "$top" "BCSActive" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr43 \
        -borderwidth 2 -relief groove -width 1005 -height 215 
    vTcl:DefineAlias "$top.tFr43" "TFrame1" vTcl:WidgetProc "BCSActive" 1
    set site_3_0 $top.tFr43
    ttk::label $site_3_0.tLa45 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Message # :} 
    vTcl:DefineAlias "$site_3_0.tLa45" "TLabel1" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Customer :} 
    vTcl:DefineAlias "$site_3_0.tLa46" "TLabel2" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa47 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Boeing Focal :} 
    vTcl:DefineAlias "$site_3_0.tLa47" "TLabel3" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn48 \
        -textvariable mNumber -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn48" "mNumber" vTcl:WidgetProc "BCSActive" 1
    bind $site_3_0.tEn48 <Enter> {
        lambda e: mNumber(e)
    }
    ttk::entry $site_3_0.tEn49 \
        -textvariable customer -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn49" "customer" vTcl:WidgetProc "BCSActive" 1
    bind $site_3_0.tEn49 <Enter> {
        lambda e: customer(e)
    }
    ttk::entry $site_3_0.tEn50 \
        -textvariable bFocal -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn50" "bFocal" vTcl:WidgetProc "BCSActive" 1
    bind $site_3_0.tEn50 <Enter> {
        lambda e: bFocal(e)
    }
    ttk::label $site_3_0.tLa51 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Product Line :} 
    vTcl:DefineAlias "$site_3_0.tLa51" "TLabel4" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa52 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Product Type :} 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel5" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa53 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Product :} 
    vTcl:DefineAlias "$site_3_0.tLa53" "TLabel6" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa54 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Subject :} 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabel7" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa55 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Messge Date :} 
    vTcl:DefineAlias "$site_3_0.tLa55" "TLabel8" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa56 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {BCS Due Date : } 
    vTcl:DefineAlias "$site_3_0.tLa56" "TLabel9" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa57 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {FTD Due Date :} 
    vTcl:DefineAlias "$site_3_0.tLa57" "TLabel10" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa58 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {FTD Lead :} 
    vTcl:DefineAlias "$site_3_0.tLa58" "TLabel11" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn60 \
        -textvariable pLine -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn60" "pLine" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn61 \
        -textvariable pType -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn61" "pType" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn62 \
        -textvariable product -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn62" "product" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn63 \
        -justify center -textvariable subject -foreground {} -background {} \
        -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn63" "subject" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn64 \
        -textvariable mDate -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn64" "mDate" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn65 \
        -textvariable bcsDueDate -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn65" "bcsDueDate" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn66 \
        -textvariable ftdDueDate -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn66" "ftdDueDate" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn67 \
        -textvariable ftdLead -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn67" "ftdLead" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa68 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Assigned Team :} 
    vTcl:DefineAlias "$site_3_0.tLa68" "TLabel12" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa69 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {FTD Team :} 
    vTcl:DefineAlias "$site_3_0.tLa69" "TLabel13" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn70 \
        -textvariable aTeam -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn70" "aTeam" vTcl:WidgetProc "BCSActive" 1
    ttk::entry $site_3_0.tEn71 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn71" "TEntry13" vTcl:WidgetProc "BCSActive" 1
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 310 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 640 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tEn48 \
        -in $site_3_0 -x 100 -y 10 -width 206 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn49 \
        -in $site_3_0 -x 390 -y 10 -width 246 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn50 \
        -in $site_3_0 -x 750 -y 10 -width 236 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 310 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 640 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 230 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.tLa57 \
        -in $site_3_0 -x 460 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 680 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 110 -y 50 -width 196 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn61 \
        -in $site_3_0 -x 420 -y 50 -width 216 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn62 \
        -in $site_3_0 -x 710 -y 50 -width 276 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn63 \
        -in $site_3_0 -x 80 -y 90 -width 906 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn64 \
        -in $site_3_0 -x 110 -y 130 -width 116 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn65 \
        -in $site_3_0 -x 340 -y 130 -width 116 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn66 \
        -in $site_3_0 -x 570 -y 130 -width 106 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn67 \
        -in $site_3_0 -x 760 -y 130 -width 226 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa68 \
        -in $site_3_0 -x 10 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.tLa69 \
        -in $site_3_0 -x 680 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.tEn70 \
        -in $site_3_0 -x 130 -y 170 -width 546 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn71 \
        -in $site_3_0 -x 770 -y 170 -width 216 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr72 \
        -borderwidth 2 -relief groove -width 1005 -height 275 
    vTcl:DefineAlias "$top.tFr72" "TFrame2" vTcl:WidgetProc "BCSActive" 1
    set site_3_0 $top.tFr72
    ttk::label $site_3_0.tLa73 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {BCS Message :} 
    vTcl:DefineAlias "$site_3_0.tLa73" "TLabel14" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa74 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Attachements :} 
    vTcl:DefineAlias "$site_3_0.tLa74" "TLabel15" vTcl:WidgetProc "BCSActive" 1
    ttk::combobox $site_3_0.tCo75 \
        -textvariable attachement -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo75" "attachment" vTcl:WidgetProc "BCSActive" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr77 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr77" "message" vTcl:WidgetProc "BCSActive" 1

    $site_3_0.scr77.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_3_0.tLa73 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tLa74 \
        -in $site_3_0 -x 590 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tCo75 \
        -in $site_3_0 -x 710 -y 10 -width 277 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr77 \
        -in $site_3_0 -x 10 -y 60 -width 975 -relwidth 0 -height 214 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr78 \
        -borderwidth 2 -relief groove -width 1005 -height 225 
    vTcl:DefineAlias "$top.tFr78" "TFrame3" vTcl:WidgetProc "BCSActive" 1
    set site_3_0 $top.tFr78
    ttk::label $site_3_0.tLa79 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {STD Email Phrase :} 
    vTcl:DefineAlias "$site_3_0.tLa79" "TLabel16" vTcl:WidgetProc "BCSActive" 1
    ttk::combobox $site_3_0.tCo80 \
        -textvariable stdPhrase -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo80" "stdPhrase" vTcl:WidgetProc "BCSActive" 1
    ttk::label $site_3_0.tLa82 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat \
        -text {Email Editor :} 
    vTcl:DefineAlias "$site_3_0.tLa82" "TLabel17" vTcl:WidgetProc "BCSActive" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr83 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr83" "email" vTcl:WidgetProc "BCSActive" 1

    $site_3_0.scr83.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_3_0.tLa79 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.tCo80 \
        -in $site_3_0 -x 150 -y 10 -width 837 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa82 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.scr83 \
        -in $site_3_0 -x 150 -y 50 -width 835 -relwidth 0 -height 154 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu84 \
        -takefocus {} -text {Create Email} 
    vTcl:DefineAlias "$top.tBu84" "createEmail" vTcl:WidgetProc "BCSActive" 1
    bind $top.tBu84 <Button-1> {
        lambda e: createEmail_1click(e)
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu85 \
        -takefocus {} -text Exit 
    vTcl:DefineAlias "$top.tBu85" "exit" vTcl:WidgetProc "BCSActive" 1
    bind $top.tBu85 <Button-1> {
        lambda e: exit_lclick(e)
    }
    set site_3_0 $top.m38
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label File 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr38 \
        -borderwidth 2 -relief groove -width 285 -height 55 
    vTcl:DefineAlias "$top.tFr38" "TFrame4" vTcl:WidgetProc "BCSActive" 1
    set site_3_0 $top.tFr38
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu39 \
        -takefocus {} -text Save 
    vTcl:DefineAlias "$site_3_0.tBu39" "save" vTcl:WidgetProc "BCSActive" 1
    bind $site_3_0.tBu39 <Button-1> {
        lambda e: save_1click(e)
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu40 \
        -takefocus {} -text Search 
    vTcl:DefineAlias "$site_3_0.tBu40" "search" vTcl:WidgetProc "BCSActive" 1
    bind $site_3_0.tBu40 <Button-1> {
        lambda e: search_1click(e)
    }
    place $site_3_0.tBu39 \
        -in $site_3_0 -x 10 -y 10 -width 98 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu40 \
        -in $site_3_0 -x 180 -y 10 -width 98 -height 30 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr43 \
        -in $top -x 10 -y 20 -width 1005 -relwidth 0 -height 215 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr72 \
        -in $top -x 10 -y 250 -width 1005 -relwidth 0 -height 275 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tFr78 \
        -in $top -x 10 -y 540 -width 1005 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu84 \
        -in $top -x 460 -y 780 -width 128 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu85 \
        -in $top -x 940 -y 774 -width 78 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr38 \
        -in $top -x 10 -y 770 -width 285 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

